/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.26.3-g9b7e726 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.26.3-g9b7e726"
#endif
#define SDL_REVISION_NUMBER 0
